[tool.poetry]
name = "hypnos"
version = "0.1.0"
description = ""
authors = ["VJean"]
readme = "readme.md"

[tool.poetry.dependencies]
python = "~3.7"
Flask = "1.1.2"
Flask-Bcrypt = "0.7.1"
Flask-Login = "0.5.0"
Flask-Migrate = "2.5.3"
Flask-Script = "2.0.6"
Flask-SQLAlchemy = "2.4.1"
Flask-WTF = "0.14.3"
WTForms-Alchemy = "0.16.9"
WTForms-Components = "0.10.4"
isodate = "0.6.0"
requests = "2.23.0"
pendulum = "2.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
