"""Initial migration

Revision ID: 13b09aff19df
Revises: 
Create Date: 2022-11-26 10:10:23.031654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13b09aff19df'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nights', schema=None) as batch_op:
        batch_op.alter_column('day',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('sleepless',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('alone',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('place_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_unique_constraint(None, ['to_rise'])
        batch_op.create_unique_constraint(None, ['to_bed'])

    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_places_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nights', schema=None) as batch_op:
        batch_op.drop_constraint('uq_nights_to_rise', type_='unique')
        batch_op.drop_constraint('uq_nights_to_bed', type_='unique')
        batch_op.alter_column('place_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('alone',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('sleepless',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('day',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###
