"""Add archived column for places

Revision ID: 3b4f6248d2d6
Revises: 13b09aff19df
Create Date: 2022-11-26 15:01:18.947584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b4f6248d2d6'
down_revision = '13b09aff19df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nights', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_nights_day'), ['day'])

    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.drop_column('archived')

    with op.batch_alter_table('nights', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_nights_day'), type_='unique')

    # ### end Alembic commands ###
