"""Add archived column to places

Revision ID: 8d4773ad4ccc
Revises: 13b09aff19df
Create Date: 2022-11-26 15:27:10.413149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d4773ad4ccc'
down_revision = '13b09aff19df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nights', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_nights_day'), ['day'])

    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.drop_column('archived')

    with op.batch_alter_table('nights', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_nights_day'), type_='unique')

    # ### end Alembic commands ###
